name: Test workflow
on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest #we can use windows / linux or macos
    steps:
      - uses: actions/checkout@v3 #https://github.com/marketplace/actions/checkout
      - uses: actions/setup-node@v3 #https://github.com/marketplace/actions/setup-node-js-environment
        with:
          node-version: 16
      - run: npm ci #clean install (package-lock.json)
      - run: npm run build
      - run: npm test #launch unit tests
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "matthieucmp/jokes-app" #Must be unique in Heroku
          heroku_email: "campagne.matthieu@gmail.com"


    #55420263-8503-42c0-aa36-5dbf7ff5a9f6